# Generated by Django 3.2.13 on 2022-05-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rental')),
            ],
            options={
                'ordering': ['checkin'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['checkin'], name='core_reserv_checkin_9f24bc_idx'),
        ),
    ]
